# Generated by Django 5.1.6 on 2025-03-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_cancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cancelado',
        ),
    ]
